name: 'Check spelling'
on: [pull_request, push]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v4
